### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by silvamari** [spencerthayer/ezIPTV#1]
When trying to deploy to heroku, it is saying that no app.json found.

**Comment by LiamKenyon** [comment]
Getting the same error and then also asking for login details on the app if you try and pull from github.

**Comment by tMHwFFopPNEY** [comment]
Just doesn't work.  Missing a json file.

**Comment by spencerthayer** [comment]
Yes. I the Reddit discussion I mention that I disabled deployment to Heroku for a second due to security error. I'll have this fixed by tonight.

**Comment by spencerthayer** [comment]
Okay, I turned it back on for Heroku development. The security error was for people running ezIPTV in a subdirectory but frankly, fuck it, I am not going to try and fix this to work with something I didn't intend it to run on. If anyone wants to this run on a subdirectory contribute to the code. For everyone else using Heroku, this works totally fine.

**Comment by spencerthayer** [comment]
Dealing with domain URL paths with PHP is a nightmare and not worth my time.
